---
# tasks file for debops.composer

- name: Download composer.phar
  get_url:
    url: '{{ composer_url  }}'
    dest: '{{ composer_bin_path }}'
    force: true
    mode: '0755'
  creates: '{{ composer_bin_path }}'

- name: Set up system-wide composer home
  file:
    path: '{{ composer_system_home }}'
    state: 'directory'
    mode: '0755'

- name: Set up system-wide composer.json
  file:
    path: '{{ composer_system_home }}/composer.json'
    state: 'touch'
    mode: '0644'

- name: Set up composer bin-dir
  shell: >
    {{ composer_bin_path }} config bin-dir {{ composer_system_bin_dir }}
    --working-dir {{ composer_system_home }}

- name: Install system-wide composer packages
  shell: >
    {{ composer_bin_path }} require {{ item.name }}:{{ item.release|default("@stable") }} 
    --no-progress --working-dir {{ composer_system_home }}
  with_items: composer_system_packages
