---
# tasks file for debops.composer

- name: Download composer.phar
  get_url:
    url: '{{ composer_url  }}'
    dest: '{{ composer_bin_path }}'
    mode: '0755'

- name: Install composer packages
  include: 'packages.yml'
  when: (composer_user|d() and composer_packages|d())
